# Generated by Django 5.1.3 on 2024-11-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_diario', models.CharField(max_length=30)),
                ('data', models.CharField(max_length=50)),
                ('registro', models.DateField()),
            ],
        ),
    ]
