# Generated by Django 5.1.3 on 2024-11-29 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0004_alter_fluxoagua_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxoagua',
            name='hora',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Hora'),
        ),
    ]
