# Generated by Django 5.1.3 on 2024-11-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0005_alter_fluxoagua_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxoagua',
            name='hora',
            field=models.TimeField(default='00:00', verbose_name='Hora'),
        ),
    ]
