# Generated by Django 5.1.3 on 2024-11-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0006_alter_fluxoagua_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
