# Generated by Django 5.1.3 on 2024-11-29 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0007_consumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluxoagua',
            name='consumo_diario',
        ),
        migrations.RemoveField(
            model_name='fluxoagua',
            name='data',
        ),
        migrations.RemoveField(
            model_name='fluxoagua',
            name='hora',
        ),
        migrations.AddField(
            model_name='fluxoagua',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fluxoagua',
            name='litros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
