# Generated by Django 5.1.3 on 2024-11-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0008_remove_fluxoagua_consumo_diario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxoagua',
            name='litros',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
