# Generated by Django 5.1.3 on 2024-11-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0009_alter_fluxoagua_litros'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoDiarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('consumo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hora', models.TimeField()),
            ],
        ),
    ]
