# Generated by Django 5.1.3 on 2024-11-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0010_consumodiariomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxoagua',
            name='litros',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
