# Generated by Django 5.1.3 on 2024-11-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0012_rename_consumodiariomodel_consumodiario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consumo',
        ),
    ]
