# Generated by Django 5.1.3 on 2024-11-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0013_delete_consumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumodiario',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
