# Generated by Django 5.1.3 on 2024-12-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0014_alter_consumodiario_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxoagua',
            name='valor_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
