# Generated by Django 5.1.3 on 2024-12-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0015_fluxoagua_valor_atual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluxoagua',
            name='valor_atual',
        ),
    ]
