# Generated by Django 5.1.3 on 2024-12-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0016_remove_fluxoagua_valor_atual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fluxoagua',
            old_name='consumo_diario',
            new_name='valor',
        ),
    ]
